/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	time "time"

	kaos_v1 "github.com/arnaudmz/kaos/pkg/apis/kaos/v1"
	versioned "github.com/arnaudmz/kaos/pkg/client/clientset/versioned"
	internalinterfaces "github.com/arnaudmz/kaos/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/arnaudmz/kaos/pkg/client/listers/kaos/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KaosRuleInformer provides access to a shared informer and lister for
// KaosRules.
type KaosRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KaosRuleLister
}

type kaosRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKaosRuleInformer constructs a new informer for KaosRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKaosRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKaosRuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKaosRuleInformer constructs a new informer for KaosRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKaosRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KaosV1().KaosRules(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KaosV1().KaosRules(namespace).Watch(options)
			},
		},
		&kaos_v1.KaosRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *kaosRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKaosRuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kaosRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kaos_v1.KaosRule{}, f.defaultInformer)
}

func (f *kaosRuleInformer) Lister() v1.KaosRuleLister {
	return v1.NewKaosRuleLister(f.Informer().GetIndexer())
}
